1. Challenge 1:

- Answer: b
- Explanation: the output is xyz 2x because let foo get resigned in the function and get called in the function and outside the resigned foo

2. Challenge 2:

- Answer: C
- Explanation: the function get called and the value resigned to 10, and the resignuing just happend inside the function and stay in the scope, doesnt become globale.

3. Challenge 3:

- Answer: C
- Explanation: before ES6 you could call the function before declare

4. Challenge 4:

- Answer: C
- Explanation: because b= a and the memory is just looking fir b, not what is inside of the ojt. Therefore you can resign it

5. Bonus - Challenge 5:

- Answer:
- Explanation:
