1. Challenge 1:

- Answer: d
- Explanation: ReferenceError because foo is being created with let keyword so scope is not global.

2. Challenge 2:

- Answer: c
- Explanation: a is defined as 1 outside the function scope, but inside is 10.

3. Challenge 3:

- Answer: b
- Explanation: Undefined because the function is called before its creation

4. Challenge 4:

- Answer: a
- Explanation: Variable a is a const which means its value cannot be updated

5. Bonus - Challenge 5:

- Answer: a
- Explanation:
